# src/tabs/tab_callgraph.py
# Tab 1: Call Graph Analysis

import os
import re
import base64
import tempfile
import subprocess
import streamlit as st
import streamlit.components.v1 as components


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def demangle_dot(dot_content):
    """
    Demangle C++ mangled names in dot file safely.
    Strips parameter types to avoid dot syntax errors.
    e.g. _Z14generateReportPKc → generateReport
    """
    def replace_mangled(match):
        name = match.group(0).strip('"')
        result = subprocess.run(
            ['c++filt', name],
            capture_output=True, text=True
        )
        clean = result.stdout.strip()
        clean = clean.split('(')[0]   # remove parameter types
        clean = clean.split('::')[-1] # remove namespace prefix
        return f'"{clean}"'

    return re.sub(r'"?_Z\w+"?', replace_mangled, dot_content)


def run_llvm_callgraph(cpp_file_path, project_root, results_dir):
    """
    Run LLVM CallGraph tool on a C++ file.
    Returns: (png_path, error_message)
    """
    callgraph_script = os.path.join(project_root, "CallGraph", "run.sh")

    try:
        # Step 1: Run run.sh → generates graph.dot + graph.text
        result = subprocess.run(
            ["bash", callgraph_script, cpp_file_path],
            capture_output=True,
            text=True,
            cwd=project_root
        )

        if result.returncode != 0:
            return None, f"LLVM Error:\n{result.stderr}"

        # Check graph.dot exists
        dot_path = os.path.join(project_root, "graph.dot")
        if not os.path.exists(dot_path):
            return None, "graph.dot not generated by LLVM"

        # Step 2: Demangle names and render to PNG
        clean_dot_path = os.path.join(results_dir, "graph_clean.dot")
        with open(dot_path, 'r') as f:
            dot_content = f.read()

        clean_content = demangle_dot(dot_content)
        with open(clean_dot_path, 'w') as f:
            f.write(clean_content)

        png_path = os.path.join(results_dir, "callgraph.png")
        render_result = subprocess.run(
            ["dot", "-Tpng", clean_dot_path, "-o", png_path],
            capture_output=True,
            text=True
        )

        if render_result.returncode != 0:
            return None, f"Graphviz Error:\n{render_result.stderr}"

        return png_path, None

    except FileNotFoundError as e:
        return None, f"Tool not found: {e}\nMake sure LLVM and Graphviz are installed."
    except Exception as e:
        return None, f"Unexpected error: {e}"


def save_uploaded_file(uploaded_file, suffix='.cpp'):
    """Save Streamlit uploaded file to a temp location."""
    tmp = tempfile.NamedTemporaryFile(
        suffix=suffix,
        delete=False,
        dir='/tmp'
    )
    tmp.write(uploaded_file.read())
    tmp.close()
    return tmp.name


def render_zoomable_image(png_path):
    """Render a PNG image with mouse wheel zoom and drag-to-pan."""
    with open(png_path, "rb") as img_f:
        encoded = base64.b64encode(img_f.read()).decode()

    zoom_html = f"""
<div style="
    overflow: hidden;
    width: 100%;
    height: 600px;
    border: 1px solid #ddd;
    border-radius: 8px;
    background: #fafafa;
    position: relative;
    cursor: grab;
">
    <div id="zoom_container" style="
        transform-origin: top left;
        position: absolute;
        top: 0; left: 0;
    ">
        <img src="data:image/png;base64,{encoded}"
             id="callgraph_img"
             style="display: block; width: 100%;"
        />
    </div>
</div>
<p style="font-size:12px; color:gray; margin-top:4px;">
    🖱️ Scroll to zoom &nbsp;|&nbsp; Click + drag to pan &nbsp;|&nbsp; Double-click to reset
</p>
<script>
    const container = document.getElementById('zoom_container');
    const wrapper   = container.parentElement;

    let scale = 1, posX = 0, posY = 0;
    let dragging = false, startX, startY;

    wrapper.addEventListener('wheel', function(e) {{
        e.preventDefault();
        const delta = e.deltaY > 0 ? -0.1 : 0.1;
        scale = Math.min(Math.max(0.3, scale + delta), 5);
        container.style.transform = `translate(${{posX}}px, ${{posY}}px) scale(${{scale}})`;
    }}, {{ passive: false }});

    wrapper.addEventListener('mousedown', function(e) {{
        dragging = true;
        startX = e.clientX - posX;
        startY = e.clientY - posY;
        wrapper.style.cursor = 'grabbing';
    }});
    window.addEventListener('mousemove', function(e) {{
        if (!dragging) return;
        posX = e.clientX - startX;
        posY = e.clientY - startY;
        container.style.transform = `translate(${{posX}}px, ${{posY}}px) scale(${{scale}})`;
    }});
    window.addEventListener('mouseup', function() {{
        dragging = false;
        wrapper.style.cursor = 'grab';
    }});
    wrapper.addEventListener('dblclick', function() {{
        scale = 1; posX = 0; posY = 0;
        container.style.transform = `translate(0px, 0px) scale(1)`;
    }});
</script>
"""
    components.html(zoom_html, height=640)


# ============================================================
# MAIN RENDER FUNCTION
# ============================================================

def render_callgraph_tab(cpp_path, file_label, project_root, results_dir):
    """Main render function called from dashboard.py"""

    st.header("Call Graph Analysis")
    st.write("Generates a static call graph using LLVM/Clang static analysis.")

    # Show selected file
    if file_label:
        st.info(f"Selected file: `{file_label}`")
    else:
        st.warning("Please upload a C++ file or enable sample files.")

    # Session state init
    if 'callgraph_png' not in st.session_state:
        st.session_state.callgraph_png = None

    # Analyze button
    if st.button("Generate Call Graph", type="primary"):
        if cpp_path is None:
            st.error("No file selected.")
        else:
            with st.spinner("Running LLVM analysis... this may take a few seconds"):
                png_path, error = run_llvm_callgraph(
                    cpp_path, project_root, results_dir
                )
            if error:
                st.error(f"Error:\n\n{error}")
            elif png_path and os.path.exists(png_path):
                st.session_state.callgraph_png = png_path
                st.success("Call graph generated successfully!")
            else:
                st.error("Call graph image not found after analysis.")

    # Display graph (persists via session state)
    if st.session_state.callgraph_png and os.path.exists(st.session_state.callgraph_png):
        png_path = st.session_state.callgraph_png

        render_zoomable_image(png_path)

        # Download button
        with open(png_path, 'rb') as f:
            st.download_button(
                label="Download Call Graph",
                data=f,
                file_name="callgraph.png",
                mime="image/png"
            )

        # Raw data expander
        txt_path = os.path.join(project_root, "graph.text")
        if os.path.exists(txt_path):
            with st.expander("View raw call graph data"):
                with open(txt_path, 'r') as f:
                    st.code(f.read(), language='text')

    # Info box
    with st.expander("About Call Graph Analysis"):
        st.markdown("""
        **What is a Call Graph?**
        A directed graph showing which functions call which other functions.

        **How it's generated:**
        - Uses LLVM/Clang static analysis (not regex)
        - Compiles the file to LLVM IR, then analyzes call instructions
        - Function names are demangled using `c++filt`

        **What to look for:**
        - Functions with many outgoing calls (high fan-out) = complex, risky
        - Functions called by many others (high fan-in) = critical, high impact if buggy

        **Reference:** Grove et al. (1997) "Call Graph Construction in Object-Oriented Languages"
        """)