# src/tabs/tab_callgraph.py
# Tab 1: Call Graph Analysis
# Feature 1: Full file call graph (LLVM)
# Feature 2: Function-specific call graph (parsed from graph.text)

import os
import re
import base64
import tempfile
import subprocess
import networkx as nx
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import streamlit as st
import streamlit.components.v1 as components


# ============================================================
# PART 1: LLVM FULL CALL GRAPH
# ============================================================

def demangle_dot(dot_content):
    """Demangle C++ mangled names in dot file safely."""
    def replace_mangled(match):
        name = match.group(0).strip('"')
        result = subprocess.run(
            ['c++filt', name], capture_output=True, text=True
        )
        clean = result.stdout.strip()
        clean = clean.split('(')[0]
        clean = clean.split('::')[-1]
        return f'"{clean}"'
    return re.sub(r'"?_Z\w+"?', replace_mangled, dot_content)


def run_llvm_callgraph(cpp_file_path, project_root, results_dir):
    """Run LLVM CallGraph tool. Returns (png_path, error)."""
    callgraph_script = os.path.join(project_root, "CallGraph", "run.sh")
    try:
        result = subprocess.run(
            ["bash", callgraph_script, cpp_file_path],
            capture_output=True, text=True, cwd=project_root
        )
        if result.returncode != 0:
            return None, f"LLVM Error:\n{result.stderr}"

        dot_path = os.path.join(project_root, "graph.dot")
        if not os.path.exists(dot_path):
            return None, "graph.dot not generated by LLVM"

        clean_dot_path = os.path.join(results_dir, "graph_clean.dot")
        with open(dot_path, 'r') as f:
            dot_content = f.read()

        clean_content = demangle_dot(dot_content)
        with open(clean_dot_path, 'w') as f:
            f.write(clean_content)

        png_path = os.path.join(results_dir, "callgraph.png")
        render_result = subprocess.run(
            ["dot", "-Tpng", clean_dot_path, "-o", png_path],
            capture_output=True, text=True
        )
        if render_result.returncode != 0:
            return None, f"Graphviz Error:\n{render_result.stderr}"

        return png_path, None

    except FileNotFoundError as e:
        return None, f"Tool not found: {e}"
    except Exception as e:
        return None, f"Unexpected error: {e}"


# ============================================================
# PART 2: FUNCTION-SPECIFIC CALL GRAPH
# ============================================================

def parse_graph_text(txt_path):
    """
    Parse LLVM graph.text into a dict.
    Format: [caller]:[callee1],[callee2]
    Returns: {caller: [callee1, callee2]}
    """
    call_map = {}
    with open(txt_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            match = re.match(r'\[(.+?)\]:\[?(.+)\]?', line)
            if not match:
                continue
            caller      = match.group(1).strip()
            callees_raw = match.group(2).strip()
            callees     = re.findall(r'\[?([^\[\],]+)\]?', callees_raw)
            callees     = [c.strip() for c in callees if c.strip()]
            call_map[caller] = callees
    return call_map


def demangle_name(name):
    """Demangle a single C++ mangled name."""
    if not name.startswith('_Z'):
        return name
    result = subprocess.run(
        ['c++filt', name], capture_output=True, text=True
    )
    clean = result.stdout.strip()
    clean = clean.split('(')[0]
    clean = clean.split('::')[-1]
    return clean


def demangle_map(call_map):
    """Demangle all function names in call_map."""
    clean_map = {}
    for caller, callees in call_map.items():
        clean_caller  = demangle_name(caller)
        clean_callees = [demangle_name(c) for c in callees]
        clean_map[clean_caller] = clean_callees
    return clean_map


def get_available_functions(call_map):
    """Return sorted list of all function names."""
    all_funcs = set(call_map.keys())
    for callees in call_map.values():
        all_funcs.update(callees)
    return sorted(all_funcs)


def build_function_subgraph(call_map, target_func):
    """Build subgraph centered on target_func."""
    G     = nx.DiGraph()
    roles = {}

    G.add_node(target_func)
    roles[target_func] = 'target'

    # Outgoing: target calls these
    if target_func in call_map:
        for callee in call_map[target_func]:
            G.add_node(callee)
            G.add_edge(target_func, callee)
            roles[callee] = 'callee'

    # Incoming: these call target
    for caller, callees in call_map.items():
        if caller == target_func:
            continue
        if target_func in callees:
            G.add_node(caller)
            G.add_edge(caller, target_func)
            roles[caller] = 'caller'

    return G, roles


def render_function_subgraph(G, roles, target_func, output_path):
    """Draw and save function-specific subgraph."""
    if G.number_of_nodes() == 0:
        return None

    color_map = {
        'target': '#ff6600',
        'caller': '#4488ff',
        'callee': '#44bb44',
    }
    node_colors = [color_map.get(roles.get(n, 'callee')) for n in G.nodes()]

    try:
        pos = nx.nx_agraph.graphviz_layout(G, prog='dot')
    except Exception:
        pos = nx.spring_layout(G, seed=42, k=3.0)

    fig, ax = plt.subplots(figsize=(16, 9))
    ax.set_aspect('auto')

    # Auto-fit axis limits first
    if pos:
        xs = [v[0] for v in pos.values()]
        ys = [v[1] for v in pos.values()]
        x_pad = (max(xs) - min(xs)) * 0.3 + 100
        y_pad = (max(ys) - min(ys)) * 0.3 + 80
        ax.set_xlim(min(xs) - x_pad, max(xs) + x_pad)
        ax.set_ylim(min(ys) - y_pad, max(ys) + y_pad)

    # Draw edges first
    nx.draw_networkx_edges(G, pos, ax=ax, arrows=True,
                           arrowsize=20, edge_color='#555555',
                           connectionstyle='arc3,rad=0.05',
                           min_source_margin=45, min_target_margin=45)

    # Draw elliptical nodes using ax.transData + FancyBboxPatch
    renderer = fig.canvas.get_renderer()
    for node in G.nodes():
        x, y  = pos[node]
        role  = roles.get(node, 'callee')
        color = color_map.get(role, '#44bb44')
        label = node

        # Measure text width to size ellipse dynamically
        txt = ax.text(x, y, label, ha='center', va='center',
                      fontsize=9, fontweight='bold', color='white',
                      zorder=5)

        # Get text bounding box in display coords, convert to data coords
        fig.canvas.draw()
        bbox = txt.get_window_extent(renderer=renderer)
        inv  = ax.transData.inverted()
        bbox_data = inv.transform([[bbox.x0, bbox.y0],
                                   [bbox.x1, bbox.y1]])
        w = (bbox_data[1][0] - bbox_data[0][0]) * 1.8
        h = (bbox_data[1][1] - bbox_data[0][1]) * 2.8

        ellipse = mpatches.Ellipse(
            (x, y), width=max(w, 60), height=max(h, 25),
            facecolor=color, edgecolor='white',
            linewidth=1.5, alpha=0.95, zorder=4
        )
        ax.add_patch(ellipse)
        txt.set_zorder(5)

    ax.set_title(f"Call Graph: {target_func}()",
                 fontsize=14, fontweight='bold', pad=15)
    ax.axis('off')

    legend_items = [
        mpatches.Patch(color='#4488ff', label='Callers (call this function)'),
        mpatches.Patch(color='#ff6600', label=f'{target_func} (selected)'),
        mpatches.Patch(color='#44bb44', label='Callees (called by this function)'),
    ]
    ax.legend(handles=legend_items, loc='upper right',
              fontsize=10, framealpha=0.9)

    plt.tight_layout()
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    plt.close()
    return output_path


# ============================================================
# SHARED: ZOOMABLE IMAGE
# ============================================================

def render_zoomable_image(png_path, height=640):
    """Render PNG with mouse wheel zoom and drag-to-pan."""
    with open(png_path, "rb") as img_f:
        encoded = base64.b64encode(img_f.read()).decode()

    uid = os.path.basename(png_path).replace('.', '_')
    html = f"""
<div style="overflow:hidden; width:100%; height:{height}px;
            border:1px solid #ddd; border-radius:8px;
            background:#fafafa; position:relative; cursor:grab;">
    <div id="zc_{uid}" style="transform-origin:top left;
                               position:absolute; top:0; left:0;">
        <img src="data:image/png;base64,{encoded}"
             style="display:block; width:100%;"/>
    </div>
</div>
<p style="font-size:12px; color:gray; margin-top:4px;">
    🖱️ Scroll to zoom &nbsp;|&nbsp; Click + drag to pan &nbsp;|&nbsp; Double-click to reset
</p>
<script>
(function() {{
    const c = document.getElementById('zc_{uid}');
    const w = c.parentElement;
    let scale=1, px=0, py=0, drag=false, sx, sy;
    w.addEventListener('wheel', e => {{
        e.preventDefault();
        scale=Math.min(Math.max(0.3,scale+(e.deltaY>0?-0.1:0.1)),5);
        c.style.transform=`translate(${{px}}px,${{py}}px) scale(${{scale}})`;
    }}, {{passive:false}});
    w.addEventListener('mousedown', e => {{
        drag=true; sx=e.clientX-px; sy=e.clientY-py;
        w.style.cursor='grabbing';
    }});
    window.addEventListener('mousemove', e => {{
        if(!drag) return;
        px=e.clientX-sx; py=e.clientY-sy;
        c.style.transform=`translate(${{px}}px,${{py}}px) scale(${{scale}})`;
    }});
    window.addEventListener('mouseup',()=>{{drag=false;w.style.cursor='grab';}});
    w.addEventListener('dblclick',()=>{{
        scale=1;px=0;py=0;
        c.style.transform='translate(0px,0px) scale(1)';
    }});
}})();
</script>
"""
    components.html(html, height=height + 30)


# ============================================================
# MAIN RENDER FUNCTION
# ============================================================

def render_callgraph_tab(cpp_path, file_label, project_root, results_dir):
    """Main render function called from dashboard.py"""

    st.header("📌 Call Graph Analysis")
    st.write("Generates static call graphs using LLVM/Clang analysis.")

    if file_label:
        st.info(f"📄 Selected file: `{file_label}`")
    else:
        st.warning("Please upload a C++ file or enable sample files.")

    # Session state
    for key in ['callgraph_png', 'func_subgraph_png', 'call_map']:
        if key not in st.session_state:
            st.session_state[key] = None

    # ── Feature 1: Full Call Graph ─────────────────────────────
    st.subheader("1️⃣ Full File Call Graph")
    st.caption("Shows all function call relationships in the entire file.")

    if st.button("🚀 Generate Full Call Graph", type="primary",
                 key="btn_full_cg"):
        if cpp_path is None:
            st.error("No file selected.")
        else:
            with st.spinner("Running LLVM analysis..."):
                png_path, error = run_llvm_callgraph(
                    cpp_path, project_root, results_dir
                )
            if error:
                st.error(f"❌ {error}")
            elif png_path and os.path.exists(png_path):
                st.session_state.callgraph_png = png_path
                # Parse graph.text for Feature 2
                txt_path = os.path.join(project_root, "graph.text")
                if os.path.exists(txt_path):
                    raw_map   = parse_graph_text(txt_path)
                    clean_map = demangle_map(raw_map)
                    st.session_state.call_map = clean_map
                st.success("✅ Full call graph generated!")
            else:
                st.error("Call graph image not found.")

    if st.session_state.callgraph_png and \
       os.path.exists(st.session_state.callgraph_png):
        render_zoomable_image(st.session_state.callgraph_png, height=650)
        with open(st.session_state.callgraph_png, 'rb') as f:
            st.download_button("⬇️ Download Full Call Graph", data=f,
                               file_name="callgraph.png", mime="image/png",
                               key="dl_full_cg")

    st.divider()

    # ── Feature 2: Function-Specific Call Graph ────────────────
    st.subheader("2️⃣ Function-Specific Call Graph")
    st.caption("Focused view: who calls the function + what it calls.")

    if st.session_state.call_map is None:
        st.info("👆 Generate the Full Call Graph first to enable this feature.")
    else:
        call_map   = st.session_state.call_map
        func_names = get_available_functions(call_map)

        col1, col2 = st.columns([3, 1])
        with col1:
            typed = st.text_input(
                "Type function name",
                placeholder="e.g. generateReport, loadCSV..."
            )
        with col2:
            selected = st.selectbox(
                "Or pick from list",
                options=["— select —"] + func_names
            )

        # Resolve target
        target_func = None
        if typed.strip():
            target_func = typed.strip()
        elif selected != "— select —":
            target_func = selected

        if target_func:
            st.caption(f"Target: **`{target_func}`**")

        if st.button("🔍 Generate Function Call Graph", type="primary",
                     key="btn_func_cg"):
            if not target_func:
                st.warning("Please enter or select a function name.")
            elif target_func not in call_map and \
                 not any(target_func in v for v in call_map.values()):
                st.error(f"❌ `{target_func}` not found.")
                st.info(f"Available: {', '.join(func_names[:10])}...")
            else:
                with st.spinner(f"Building subgraph for {target_func}..."):
                    G, roles  = build_function_subgraph(call_map, target_func)
                    out_path  = os.path.join(results_dir, "func_subgraph.png")
                    render_function_subgraph(G, roles, target_func, out_path)
                    st.session_state.func_subgraph_png = out_path

                callers = [n for n, r in roles.items() if r == 'caller']
                callees = [n for n, r in roles.items() if r == 'callee']
                st.success(
                    f"✅ `{target_func}` — "
                    f"called by **{len(callers)}** | "
                    f"calls **{len(callees)}**"
                )

                c1, c2 = st.columns(2)
                with c1:
                    st.markdown("**🔵 Callers (call this function):**")
                    if callers:
                        for c in callers: st.markdown(f"- `{c}`")
                    else:
                        st.caption("No callers in this file")
                with c2:
                    st.markdown("**🟢 Callees (called by this function):**")
                    if callees:
                        for c in callees: st.markdown(f"- `{c}`")
                    else:
                        st.caption("No outgoing calls")

        if st.session_state.func_subgraph_png and \
           os.path.exists(st.session_state.func_subgraph_png):
            render_zoomable_image(
                st.session_state.func_subgraph_png, height=550
            )
            with open(st.session_state.func_subgraph_png, 'rb') as f:
                st.download_button(
                    "⬇️ Download Function Call Graph", data=f,
                    file_name="func_callgraph.png", mime="image/png",
                    key="dl_func_cg"
                )

    # Info box
    with st.expander("ℹ️ About Call Graph Analysis"):
        st.markdown("""
        **Feature 1 — Full Call Graph:**
        All function relationships in the file. Generated via LLVM IR analysis.

        **Feature 2 — Function-Specific:**
        - 🔵 **Blue** = callers (functions that call the selected function)
        - 🟠 **Orange** = selected function
        - 🟢 **Green** = callees (functions the selected function calls)

        **Reference:** Grove et al. (1997) "Call Graph Construction in Object-Oriented Languages"
        """)