# src/dashboard.py
# CommitFuzz - Interactive Dashboard
# Built with Streamlit

import streamlit as st
import subprocess
import tempfile
import os
import shutil
import re

# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="CommitFuzz",
    page_icon="🔍",
    layout="wide"
)

# ============================================================
# PATHS
# ============================================================

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CALLGRAPH_SCRIPT = os.path.join(PROJECT_ROOT, "CallGraph", "run.sh")
RESULTS_DIR = os.path.join(PROJECT_ROOT, "results")
os.makedirs(RESULTS_DIR, exist_ok=True)

# ============================================================
# SESSION STATE
# ============================================================

if 'callgraph_png' not in st.session_state:
    st.session_state.callgraph_png = None


# ============================================================
# CALL GRAPH FUNCTIONS
# ============================================================

def demangle_dot(dot_content):
    """
    Demangle C++ mangled names in dot file safely.
    Strips parameter types to avoid dot syntax errors.
    e.g. _Z14generateReportPKc → generateReport
    """
    def replace_mangled(match):
        name = match.group(0).strip('"')
        result = subprocess.run(
            ['c++filt', name],
            capture_output=True, text=True
        )
        clean = result.stdout.strip()
        # Remove parameter types e.g. generateReport(const char*) → generateReport
        clean = clean.split('(')[0]
        # Remove any namespace prefixes if desired
        clean = clean.split('::')[-1]
        return f'"{clean}"'

    return re.sub(r'"?_Z\w+"?', replace_mangled, dot_content)


def run_llvm_callgraph(cpp_file_path):
    """
    Run LLVM CallGraph tool on a C++ file.
    Returns: path to callgraph.png or None on error
    """
    try:
        # Step 1: Run run.sh → generates graph.dot + graph.text
        result = subprocess.run(
            ["bash", CALLGRAPH_SCRIPT, cpp_file_path],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT
        )

        if result.returncode != 0:
            return None, f"LLVM Error:\n{result.stderr}"

        # Check graph.dot exists
        dot_path = os.path.join(PROJECT_ROOT, "graph.dot")
        if not os.path.exists(dot_path):
            return None, "graph.dot not generated by LLVM"

        # Step 2: Demangle names safely and render to PNG
        clean_dot_path = os.path.join(RESULTS_DIR, "graph_clean.dot")
        with open(dot_path, 'r') as f:
            dot_content = f.read()

        clean_content = demangle_dot(dot_content)
        with open(clean_dot_path, 'w') as f:
            f.write(clean_content)

        png_path = os.path.join(RESULTS_DIR, "callgraph.png")
        render_result = subprocess.run(
            ["dot", "-Tpng", clean_dot_path, "-o", png_path],
            capture_output=True,
            text=True
        )

        if render_result.returncode != 0:
            return None, f"Graphviz Error:\n{render_result.stderr}"

        return png_path, None

    except FileNotFoundError as e:
        return None, f"Tool not found: {e}\nMake sure LLVM and Graphviz are installed."
    except Exception as e:
        return None, f"Unexpected error: {e}"


def save_uploaded_file(uploaded_file):
    """Save Streamlit uploaded file to a temp location."""
    tmp = tempfile.NamedTemporaryFile(
        suffix='.cpp',
        delete=False,
        dir='/tmp'
    )
    tmp.write(uploaded_file.read())
    tmp.close()
    return tmp.name


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.image(
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/LSU_Tigers_logo.svg/200px-LSU_Tigers_logo.svg.png",
    width=80
)
st.sidebar.title("CommitFuzz")
st.sidebar.caption("Commit-Level Risk Scoring & Visualization")
st.sidebar.divider()

# File uploaders
st.sidebar.subheader("📁 Upload Files")
uploaded_cpp = st.sidebar.file_uploader(
    "C++ Source File (for Call Graph)",
    type=['cpp', 'c', 'h'],
    help="Upload any C/C++ source file to generate its call graph"
)

st.sidebar.divider()
st.sidebar.subheader("📊 Commit Analysis")
uploaded_before = st.sidebar.file_uploader(
    "Before Commit (.cpp)",
    type=['cpp', 'c'],
    key="before"
)
uploaded_after = st.sidebar.file_uploader(
    "After Commit (.cpp)",
    type=['cpp', 'c'],
    key="after"
)

# Use sample files if nothing uploaded
st.sidebar.divider()
use_sample = st.sidebar.checkbox("Use sample files (data_analyzer V1/V2)", value=True)

if use_sample:
    sample_cpp    = os.path.join(PROJECT_ROOT, "data", "data_analyzer_V1.cpp")
    sample_before = os.path.join(PROJECT_ROOT, "data", "data_analyzer_V1.cpp")
    sample_after  = os.path.join(PROJECT_ROOT, "data", "data_analyzer_V2.cpp")


# ============================================================
# MAIN AREA - TABS
# ============================================================

st.title("🔍 CommitFuzz: Commit-Level Risk Scoring")
st.caption("A static analysis tool for predicting bug introduction from code changes")
st.divider()

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📌 Call Graph",
    "🌊 Differential CFG",
    "🌡️ Risk Heatmap",
    "📊 Risk Score",
    "💡 Actionable Insights"
])


# ============================================================
# TAB 1: CALL GRAPH
# ============================================================

with tab1:
    st.header("📌 Call Graph Analysis")
    st.write("Generates a static call graph using LLVM/Clang analysis.")

    # Determine which file to use
    if uploaded_cpp is not None:
        cpp_path = save_uploaded_file(uploaded_cpp)
        file_label = uploaded_cpp.name
    elif use_sample and os.path.exists(sample_cpp):
        cpp_path = sample_cpp
        file_label = "data_analyzer_V1.cpp (sample)"
    else:
        cpp_path = None
        file_label = None

    # Show selected file
    if file_label:
        st.info(f"📄 Selected file: `{file_label}`")
    else:
        st.warning("Please upload a C++ file or enable sample files.")

    # Analyze button
    analyze_btn = st.button("🚀 Generate Call Graph", type="primary")

    if analyze_btn:
        if cpp_path is None:
            st.error("No file selected.")
        else:
            with st.spinner("Running LLVM analysis... this may take a few seconds"):
                png_path, error = run_llvm_callgraph(cpp_path)

            if error:
                st.error(f"❌ Error generating call graph:\n\n{error}")
            elif png_path and os.path.exists(png_path):
                st.session_state.callgraph_png = png_path  # save to session state
                st.success("✅ Call graph generated successfully!")
            else:
                st.error("Call graph image not found after analysis.")

    # Display graph from session state (persists across reruns)
    if st.session_state.callgraph_png and os.path.exists(st.session_state.callgraph_png):
        png_path = st.session_state.callgraph_png

        # Display the image with mouse wheel zoom
        import base64
        with open(png_path, "rb") as img_f:
            encoded = base64.b64encode(img_f.read()).decode()

        zoom_html = f"""
<div style="
    overflow: hidden;
    width: 100%;
    height: 600px;
    border: 1px solid #ddd;
    border-radius: 8px;
    background: #fafafa;
    position: relative;
    cursor: grab;
">
    <div id="zoom_container" style="
        transform-origin: top left;
        position: absolute;
        top: 0; left: 0;
    ">
        <img src="data:image/png;base64,{encoded}"
             id="callgraph_img"
             style="display: block; width: 100%;"
        />
    </div>
</div>
<p style="font-size:12px; color:gray; margin-top:4px;">
    🖱️ Scroll to zoom &nbsp;|&nbsp; Click + drag to pan &nbsp;|&nbsp; Double-click to reset
</p>
<script>
    const container = document.getElementById('zoom_container');
    const wrapper   = container.parentElement;

    let scale = 1, posX = 0, posY = 0;
    let dragging = false, startX, startY;

    wrapper.addEventListener('wheel', function(e) {{
        e.preventDefault();
        const delta = e.deltaY > 0 ? -0.1 : 0.1;
        scale = Math.min(Math.max(0.3, scale + delta), 5);
        container.style.transform = `translate(${{posX}}px, ${{posY}}px) scale(${{scale}})`;
    }}, {{ passive: false }});

    wrapper.addEventListener('mousedown', function(e) {{
        dragging = true;
        startX = e.clientX - posX;
        startY = e.clientY - posY;
        wrapper.style.cursor = 'grabbing';
    }});
    window.addEventListener('mousemove', function(e) {{
        if (!dragging) return;
        posX = e.clientX - startX;
        posY = e.clientY - startY;
        container.style.transform = `translate(${{posX}}px, ${{posY}}px) scale(${{scale}})`;
    }});
    window.addEventListener('mouseup', function() {{
        dragging = false;
        wrapper.style.cursor = 'grab';
    }});

    wrapper.addEventListener('dblclick', function() {{
        scale = 1; posX = 0; posY = 0;
        container.style.transform = `translate(0px, 0px) scale(1)`;
    }});
</script>
"""
        import streamlit.components.v1 as components
        components.html(zoom_html, height=640)

        # Download button — won't clear graph now
        with open(png_path, 'rb') as f:
            st.download_button(
                label="⬇️ Download Call Graph",
                data=f,
                file_name="callgraph.png",
                mime="image/png"
            )

        # Show raw graph.text as expandable
        txt_path = os.path.join(PROJECT_ROOT, "graph.text")
        if os.path.exists(txt_path):
            with st.expander("📄 View raw call graph data"):
                with open(txt_path, 'r') as f:
                    st.code(f.read(), language='text')

    # Info box at bottom
    with st.expander("ℹ️ About Call Graph Analysis"):
        st.markdown("""
        **What is a Call Graph?**
        A directed graph showing which functions call which other functions.

        **How it's generated:**
        - Uses LLVM/Clang static analysis (not regex)
        - Compiles the file to LLVM IR, then analyzes call instructions
        - Function names are demangled using `c++filt`

        **What to look for:**
        - Functions with many outgoing calls (high fan-out) = complex, risky
        - Functions called by many others (high fan-in) = critical, high impact if buggy

        **Reference:** Grove et al. (1997) "Call Graph Construction in Object-Oriented Languages"
        """)


# ============================================================
# TAB 2-5: PLACEHOLDERS (will build next)
# ============================================================

with tab2:
    st.header("🌊 Differential CFG")
    st.info("Coming soon — will show before/after control flow graphs side by side.")

with tab3:
    st.header("🌡️ Risk Heatmap")
    st.info("Coming soon — will show line-by-line risk coloring of code changes.")

with tab4:
    st.header("📊 Risk Score")
    st.info("Coming soon — will show cyclomatic complexity delta, flow alteration score, and change ratio.")

with tab5:
    st.header("💡 Actionable Insights")
    st.info("Coming soon — will show review checklist and high-risk lines to inspect.")